---  # default1.yaml

train_path : 'data/dataset_train.npy'
test_path : 'data/dataset_test.npy'

experiment_name: "Default Experiment"

batch_size : 16
shuffle : True
num_workers : 0
epochs: 10

checkpoint_path : ""

train : True